### ISSUE TITLE
Please specify the supported node.js versions, or, preferably, please convert the code to run on the lower versions of node.js.

### ISSUE THREAD

**Issue by zeodtr** [moxystudio/node-proper-lockfile#51]
I'm using node.js version 4.x (for some reason). I downloaded this module, and found it was not for the node.js version I use. 

Since the concept of this module is nice, I will try to convert the code using the typescript compiler to run on the node.js version I use.

But it would be nice if this module could run on the somewhat old node.js versions.

**Comment by satazor** [comment]
Node 4 will end its maintenance LTS in 7 days, see https://github.com/nodejs/Release

For that reason, you should upgrade your nodejs installation ASAP since you will no longer receive any security patches.

Having that in mind, it doesn’t make much sense to support node v4.

Makes sense?

**Comment by satazor** [comment]
Regarding the versions support, I'm open to accept a MR that adds "engine" do the package.json, see https://docs.npmjs.com/files/package.json#engines

**Comment by satazor** [comment]
If you really want to use node v4, you may use `v2.x.x` of this module.

**Comment by zeodtr** [comment]
I know that the lifetime of 4.x is ending. I have a plan to upgrade it.

Meanwhile I'll use your module by 'compiling' the source code into the old JS code using Typescript compiler. In fact it's already done and seems to work well for 4.x. Is it ok? You added a comment about v2.x.x while I'm writing this comment. I think that the 'compiled' latest code will be better than the old v2.x.x code. (bug fix, additional feature, etc.)

Thanks!

**Comment by satazor** [comment]
@zeodtr yep, compiling is better since you will be using the latest version always.

Will close this issue. Feel free to make a PR adding `engines` to package.json as I stated above.

Have a nice week!
