### ISSUE TITLE
compare speed test etc

### ISSUE THREAD

**Issue by ORESoftware** [moxystudio/node-proper-lockfile#55]
hey all

I would love to compare the functionality of this lib with my lib
https://github.com/ORESoftware/live-mutex

I haven't tried yours but I will soon. ultimately, I think a distributed lock with failover is ideal for most applications, but I guess there is a small niche for non-distributed networked locks.

**Comment by satazor** [comment]
That would be awesome, were you able to compare the performance?

Since many months have passed, I will close this for now.
