### ISSUE TITLE
Specify supported Node.js versions / transpile to es5

### ISSUE THREAD

**Issue by vgalka-sl** [moxystudio/node-proper-lockfile#57]
Hi,
Wanted to use this great package in our app which has to run on node.js v5.10.
Bumped into run-time errors due to unsupported ES6 features (destructuring).
Could you transpile it to ES5 prior to release?
In any case, it is recommended to specify the supported node versions in `package.json`.
https://stackoverflow.com/questions/29349684/how-can-i-specify-the-required-node-js-version-in-packages-json
Best regards,
Vasili

**Comment by satazor** [comment]
Node v5 is no longer maintained, see https://github.com/nodejs/Release

You may use `proper-lockfile@^2` which should support node > 4.
