### ISSUE TITLE
Pass recursive option during mkdir

### ISSUE THREAD

**Issue by dmail** [moxystudio/node-proper-lockfile#69]
Hello I had an error while using you library.

`Error: ENOENT: no such file or directory, lstat '/Users/me/folder/file.js'` occured while running the following code from  `/Users/me/` with `/Users/me/folder` not created.

```js
const lockFile = require("proper-lockfile")

lockFile.lock(`${__dirname}/folder/file.js`)
```

I guess you could pass `{recursive: true}` to mkdir here : 
https://github.com/moxystudio/node-proper-lockfile/blob/b91cb551abf74c11e59b822f42fdbb851be32db8/lib/lockfile.js#L26

The recursive option is a recent addition to nodejs api: https://nodejs.org/api/fs.html#fs_fs_mkdir_path_options_callback.

What do you think ?

**Comment by satazor** [comment]
Hello! This library expects the file you want to lock to exist by default. You can disable this behavior by disabling the realpath option. 

Let me know if that works for you.

**Comment by dmail** [comment]
My use case was to obtain a lock for a file that does not exist yet but this is not how your library is meant to be used.
I will create an empty file before trying to get a lock for the file and it's gonna be good.

**Comment by dmail** [comment]
Didn't saw your answer.
I've tried something that looks like the code below and it works:

```js
const fs = require('fs')

const getLockForFile = async (file) => {
  await new Promise((resolve, reject) => {
    fs.mkdir(path.dirname(file), { recursive: true }, (error) => {
      if (error && error.code !== 'EEXIST') reject(error)
      else resolve()
    })
  })
  return lockFile.lock(file, { realpath: false })
}

getLockForFile(`${__dirname}/folder/file.js`)
```
