### ISSUE TITLE
lockfilePath missing in interface LockOptions

### ISSUE THREAD

**Issue by hogacz** [moxystudio/node-proper-lockfile#73]
Hello, 
documentation is mentioning lockfilePath option that is exactly what I need, but it's not defined in the LockOptions interface. 
Edit: at least in index.d.ts

**Comment by satazor** [comment]
Hello,

We don’t have any index.d.ts file, maybe it’s defined in other repo?

**Comment by hogacz** [comment]
Thanks, indeed, you are right. I'm new to TS world and I thought it's a kind of bundle. Sorry.

**Comment by hogacz** [comment]
Here is a package with types: https://www.npmjs.com/package/@types/proper-lockfile
