### ISSUE TITLE
Should convert retries option to object?

### ISSUE THREAD

**Issue by alanshaw** [moxystudio/node-proper-lockfile#75]
Is this meant to be converted to an object if retries is a number?

https://github.com/moxystudio/node-proper-lockfile/blob/a66dcaf84130997b8dd7ebdfb065cc0648ac4a36/lib/lockfile.js#L205

you'll end up with `{ retries: { retries: 5 } }` for example.

**Comment by satazor** [comment]
Yes it’s correct. We accept a simple number or a more complex retry object, which has a retries field, see: https://github.com/tim-kos/node-retry/blob/master/README.md
